### ISSUE TITLE
docker-compose dont work

### ISSUE THREAD

**Issue by iMohammadd** [fandoghpaas/fandogh-cli#166]
hello
i have a docker compose project, when i want publish my image the CLI ask me a Dockerfile in root of my project!

**Comment by Anonycoders** [comment]
Hello dear @iMohammadd
Can you give us a screen shot of your terminal and also list of entities available in your directory that you are in it?

**Comment by iMohammadd** [comment]
```
version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8090:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:
```
this is my docker-compose.yml

![screenshot from 2018-10-03 09-57-17](https://user-images.githubusercontent.com/2062120/46393612-d738a880-c6f2-11e8-9e4a-2fa548e57b69.png)
and this fandogh-cli error
