### ISSUE TITLE
Service manifest proposal

### ISSUE THREAD

**Issue by s-soroosh** [fandoghpaas/fandogh-cli#34]
A service can have several properties that user can tune. 
It’s helpful to have a simple yml/json file that user can specify its service and store the infrastructure as code.

**Comment by s-soroosh** [comment]
Confirmed manifest template:

```
kind: ExternalService
 name: hello-world
 spec:
   image: hello-world:v1
   replica: 1
   port: 8080
   path: /v1/
   env:
     - name: VERSION
       value: v1
  
   domains: 
      - name: api.hello-world.com # already created domain  
        tls: api-hello-world-tls # already created certificate
        allow_http: true


   volumes:
     - name: default # already created volume
       mountPath: /mnt/data
       subPath: test
       
     - name: MyLogs # already created volume
       mountPath: /mnt/logs
       

   resources:
     limit:
       memory: 200Mi
       cpu: 0.2
       
       

 kind: InternalService
 name: hello-world
 spec:
   image: hello-world:v1
   replica: 1
   env:
     - name: VERSION
       value: v1

   volumes:
     - name: default # already created volume
       mountPath: /mnt/data
       subPath: test
     - name: MyLogs # already created volume
       mountPath: /mnt/logs
       

   resources:
     limit:
       memory: 200Mi
       cpu: 0.2



 kind: ManagedService
 name: mysql-test # in mishe hostname service
 spec:
   service_name: mysql
   version: 9.4
   parameters:
     - name: phpmyadmin_enabled   
       value: true
     - name: data_path
       value: /mnt/data/mysql-test-path
     - name: log_path
       value: /mnt/logs/mysql
   resources: #todo age chand ta container dasht pod chi? mesle mysql (badan be resources fek mikonim)
     limit:
       memory: 200Mi
       cpu: 0.2

   volumes:
     - name: default # already created volume  
       mountPath: /mnt/data
       subPath: test
     - name: MyLogs # already created volume
       mountPath: /mnt/logs
```
